services:
  app:
    tty: true
    container_name: ${APP_CONTAINER}
    build:
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./app
        target: /app
