name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
      
  envone:
  
    runs-on: ubuntu-latest
    
    name: Check required variables

    steps:
      - run: |
          if [ -z "$APP_PORT" ]; then
            echo "APP_PORT is not set"
            exit 1
          fi
  
